### ISSUE TITLE
Joint 2D-3D experiments

### ISSUE THREAD

**Issue by williamlai3a** [NVlabs/splatnet#1]
Hi, 

May I know when will the Joint 2D-3D experiments become available to try.
Thanks!

William

**Comment by varunjampani** [comment]
Because of busy schedule, we could not completely clean up the joint 2D-3D experiments. We will release them soon.

**Comment by YiruS** [comment]
> Because of busy schedule, we could not completely clean up the joint 2D-3D experiments. We will release them soon.

Would it be planed to release the 2D rendered images in ShapeNet part dataset? Thanks much!

**Comment by suhangpro** [comment]
Sorry, but as of now, we don't have a plan to release any additional data or code for this repo.
