### ISSUE TITLE
My server GPU has problem. How I can disable GPU in training and test?

### ISSUE THREAD

**Issue by hbzhang** [NVlabs/splatnet#10]
My server GPU has a problem. So I can not use GPU for training and test for now,

How I can disable GPU for training and test?

Any suggestions? Thanks!

**Comment by varunjampani** [comment]
You can try this:

import caffe
caffe.set_mode_cpu()

**Comment by hbzhang** [comment]
Thanks!  still trying to fix GPU, but will try this as last resort.
