### ISSUE TITLE
eval bug

### ISSUE THREAD

**Issue by jason718** [NVlabs/splatnet#17]
Shouldn't accuracy= TPs / (TPs+FPs)? What computed in below two lines seem to be recall.

https://github.com/NVlabs/splatnet/blob/f8219134eb4ef961b3d6c672db41490c0055a723/splatnet/semseg3d/eval_seg.py#L38

https://github.com/NVlabs/splatnet/blob/f8219134eb4ef961b3d6c672db41490c0055a723/splatnet/utils.py#L149

**Comment by suhangpro** [comment]
This is how "per-class" accuracy is typically defined for this dataset. It can be considered as "accuracy among points belonging class i"
