### ISSUE TITLE
Some bug in running facade3d in my Ubuntu16.04

### ISSUE THREAD

**Issue by FQHyuntian** [NVlabs/splatnet#2]
May I ask some issues about "module 'caffe.proto.caffe_pb2' has no attribute 'PermutohedralParameter'"?
Is there a problem with my Caffe version?

**Comment by varunjampani** [comment]
SplatNet uses 'permutohedral' layers from this repository: https://github.com/MPI-IS/bilateralNN. Did you add those layers to the caffe? You can follow these steps to add the required layers from 'bilateralNN' repo:

You can manually copy all but caffe.proto source files in bilateralNN folder to the corresponding locations in your Caffe repository. Then, for merging the caffe.proto file of bilateralNN to your version of the caffe.proto:

- copy the lines 382-383 and 854-922 in caffe.proto to the corresponding caffe.proto file in the destination Caffe repository.
- Change the parameter IDs for PermutohedralParameter and PixelFeatureParameter based on the next available LayerParameter ID in your Caffe.
