### ISSUE TITLE
Docker Env

### ISSUE THREAD

**Issue by hjwdzh** [NVlabs/splatnet#3]
I am new to docker environment. Basically, I am able to enter the docker container and use caffe. However, when I run the test script, it complains that the cuda driver version is not sufficient to cuda runtime. What is the required cuda driver? And how can I update it in docker? Thanks.

**Comment by suhangpro** [comment]
Do you have nvidia-docker (v2) installed on the host system? I think the required driver for nvidia-docker should be enough, and you shouldn't need to install anything else in the docker container.

**Comment by suhangpro** [comment]
[nvida-docker](https://github.com/NVIDIA/nvidia-docker) is a special version of docker with nvidia cuda support. Our docker image requires it instead of the standard docker.

**Comment by suhangpro** [comment]
Closing the issue. Feel free to re-open if you are still facing the problem with nvidia-docker.

**Comment by hjwdzh** [comment]
I have reinstall the nvidia-docker with the following steps.

**sudo apt-get install -y nvidia-docker2
sudo docker pull suhangpro/caffe:bpcn
sudo docker run -it suhangpro/caffe:bpcn
> pip install protobuf, scikit-image, bumpy
> git clone https://github.com/NVlabs/splatnet
> export PYTHONPATH=...
> cd /workspace/splatnet/exp/shapenet3d
> sh test_only.sh**

Then I got 

_test_only.sh: 6: test_only.sh: Bad substitution
WARNING: Logging before InitGoogleLogging() is written to STDERR
E0916 21:30:26.347004   133 common.cpp:114] Cannot create Cublas handle. Cublas won't be available.
E0916 21:30:26.347118   133 common.cpp:121] Cannot create Curand generator. Curand won't be available.
F0916 21:30:26.347223   133 common.cpp:152] Check failed: error == cudaSuccess (35 vs. 0)  CUDA driver version is insufficient for CUDA runtime version
*** Check failure stack trace: ***
Aborted (core dumped)_

Did I wrongly operate on anything?
