### ISSUE TITLE
Inconsistent cuda driver and runtime

### ISSUE THREAD

**Issue by hjwdzh** [NVlabs/splatnet#4]
I have reinstall the nvidia-docker with the following steps.

**sudo apt-get install -y nvidia-docker2
sudo docker pull suhangpro/caffe:bpcn
sudo docker run -it suhangpro/caffe:bpcn
> pip install protobuf, scikit-image, bumpy
> git clone https://github.com/NVlabs/splatnet
> export PYTHONPATH=...
> cd /workspace/splatnet/exp/shapenet3d
> sh test_only.sh**

Then I got 

_test_only.sh: 6: test_only.sh: Bad substitution
WARNING: Logging before InitGoogleLogging() is written to STDERR
E0916 21:30:26.347004   133 common.cpp:114] Cannot create Cublas handle. Cublas won't be available.
E0916 21:30:26.347118   133 common.cpp:121] Cannot create Curand generator. Curand won't be available.
F0916 21:30:26.347223   133 common.cpp:152] Check failed: error == cudaSuccess (35 vs. 0)  CUDA driver version is insufficient for CUDA runtime version
*** Check failure stack trace: ***
Aborted (core dumped)_

Did I wrongly operate on anything?

**Comment by suhangpro** [comment]
Can you verify that if have a proper nvidia-docker installation by running: 
`docker run --runtime=nvidia --rm nvidia/cuda nvidia-smi`?

It should list all availalbe gpus.

**Comment by hjwdzh** [comment]
Yes, I verified and it listed 4 gpus as expected.

**Comment by hjwdzh** [comment]
I finally find the problem. I need to add "--runtime=nvidia" when running your docker. I guess it will be helpful to give detailed description of how to run everything, since the compilation of BilateralNN is pretty tricky and hard to reproduce, and not everyone knows the usage of nvidia-docker.
