### ISSUE TITLE
nccl install

### ISSUE THREAD

**Issue by minicv123** [NVlabs/splatnet#5]
hello, I follow the step in INSTALL.md to install dependency,. when I install nccl  using command 'sudo make -j install ' it didn't work, and it shows ' make: *** No rule to make target 'install'.  Stop.'. can you please tell me how to solve it. thanks very much

**Comment by suhangpro** [comment]
According to [NCCL readme](https://github.com/NVIDIA/nccl), you should now use `make -j src.build`. Please kindly let me know if this works, and we will update our instructions!

**Comment by minicv123** [comment]
thanks, It works!
Do I need to run the rest instructions in NCCL readme?

**Comment by suhangpro** [comment]
Yes, NCCL readme has the up-to-date installation instructions. In fact, you do not need to install NCCL at all for single-gpu usages. Just skip the whole NCCL part, and change the `cmake -DUSE_CUDNN=1 -DUSE_NCCL=1 -Dpython_version=3 ..` line to `cmake -DUSE_CUDNN=1 -Dpython_version=3 ..`

**Comment by suhangpro** [comment]
Updated in commit f8219134eb4ef961b3d6c672db41490c0055a723
