### ISSUE TITLE
ImportError: No module named 'splatnet'

### ISSUE THREAD

**Issue by JennyVVV** [NVlabs/splatnet#8]
Hi, when I cd /splatnet/exp/facade3d, run SKIP_TRAIN=1 ./train_test.sh,  it reports error as follows:
Traceback (most recent call last):
  File "/home/ryxu/splatnet/exp/facade3d/../../splatnet/semseg3d/test.py", line 11, in <module>
    import splatnet.configs
**ImportError: No module named 'splatnet'**

I think maybe some wrong operation about 2.Include the project to your python path so imports can be found, I set my ./bashrc file as follows:
## caffe paths
export PYCAFFE_ROOT=/home/ryxu/caffe/python
export PYTHONPATH=$PYCAFFE_ROOT:$PYTHONPATH
export PATH=$CAFFE_ROOT/build/tools:$PYCAFFE_ROOT:$PATH
##Include the project to your python path 
export PYTHONPATH=</home/ryxu/splatnet/splatnet>:$PYTHONPATH
##
Could anyone can help me? thanks very much.

**Comment by minicv123** [comment]
try this command please : cd /splatnet
                              run SKIP_TRAIN=1  ./exp/facade3d/train_test.sh

**Comment by suhangpro** [comment]
I think you should use: `export PYTHONPATH=</home/ryxu/splatnet>:$PYTHONPATH`

**Comment by JennyVVV** [comment]
> I think you should use: `export PYTHONPATH=</home/ryxu/splatnet>:$PYTHONPATH`

I also tried your idea,  it has the same error

**Comment by minicv123** [comment]
try this:  cd /home/yt/splatnet
   run :   SKIP_TRAIN=1 ./exp/facade3d/train_test.sh
  if you first run the pre-trained model, it may occur other error

**Comment by JennyVVV** [comment]
> try this: cd /home/yt/splatnet
> run : SKIP_TRAIN=1 ./exp/facade3d/train_test.sh
> if you first run the pre-trained model, it may occur other error

Yeah, your advice is useful. Thanks very much
