### ISSUE TITLE
dataset problem

### ISSUE THREAD

**Issue by minicv123** [NVlabs/splatnet#9]
For semantic segmentation, ruemonge428 dataset is post-processed, height value is added to each point, I want to know the definition of height to each point. thanks very much!

**Comment by varunjampani** [comment]
We got height from one of the earlier works from the same group that published this dataset. See 3.1 here: https://homes.esat.kuleuven.be/~konijn/publications/2015/Martinovic_3D_All_The_2015_CVPR_paper.pdf
